function currentGUI()

    
    cols = [30,110,190,270,350];

    a = figure('Color',[0.8 0.8 0.8], ...
        'Colormap',jet, ...
        'Position',[155 150 390 280], ...
        'Tag','Fig1');

	% Callback button
	b = uicontrol('Parent',a, ...
        'Units','points', ...
        'Callback','currentBE run', ...
        'Position',[cols(1) 10 150 64], ...
        'FontSize', 20,...
        'String','Run Current', ...
        'Tag','Pushbutton1');
    

    %t_initial
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'Position',[cols(1)  140 70 15], ...
        'String','t_initial (msec)', ...
        'Style','text', ...
        'Tag','StaticText2');
    
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[cols(1)  160 70 30 ], ...
        'String','0', ...
        'Style','edit', ...
        'Tag','t_initial');
    
    % t_final
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'Position',[cols(2) 140 70 15], ...
        'String','t_final (msec)', ...
        'Style','text', ...
        'Tag','StaticText3');
    
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[cols(2) 160 70 30 ], ...
        'String','5', ...
        'Style','edit', ...
        'Tag','t_final');
    
    % t_step
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'Position',[cols(3) 140 70 15], ...
        'String','t_step', ...
        'Style','text', ...
        'Tag','StaticText4');
    
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[cols(3) 160 70 30 ], ...
        'String','0.5', ...
        'Style','edit', ...
        'Tag','t_step');

	% Variable First Simulation Amplitude 
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'Position',[cols(3) 80 70 15], ...
        'String','stim', ...
        'Style','text', ...
        'Tag','StaticText4');
    
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[cols(3) 100 70 30 ], ...
        'String','0.5', ...
        'Style','edit', ...
        'Tag','stim');

	
    % Image saving 
    b = uicontrol('Parent',a, ...
        'Units','points', ...
		'BackgroundColor',[0.7 0.7 0.7], ...
        'Position',[cols(3) 20 70 15], ...
        'String','Image Saving', ...
        'Style','text', ...
        'Tag','StaticText5');
    
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[cols(3) 40 70 30 ], ...
        'String', {'1','0'},...
        'Style','popupmenu',...
        'Tag','on1');
    
    % e_Na
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'Position',[cols(1) 80 70 15], ...
        'String','e_Na', ...
        'Style','text', ...
        'Tag','StaticText6');
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[cols(1) 100 70 30 ], ...
        'String','117.26', ...
        'Style','edit', ...
        'Tag','e_Na');
	
	% e_K
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'Position',[cols(2) 80 70 15], ...
        'String','e_K', ...
        'Style','text', ...
        'Tag','StaticText6');
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[cols(2) 100 70 30 ], ...
        'String','-12.26', ...
        'Style','edit', ...
        'Tag','e_K');
    
	
end
