function voltageGUI()
    % BME 445/545 - Developed by Dr. Keigo Kawaji kkawaji@iit.edu
    % Start FEBLAB LAB_A by calling vcgui.m for (GUI).
    % Note code object values may change when these objects are re-created, and
    % may sometimes cause some callback problems (i.e. GUI does not run).  
    % To re-open this system, just type the name of the m-file at the MATLAB
    % prompt. The M-file and its associtated MAT-file must be on your path.
    
    cols = [30,110,190,270,350];
    
    a = figure('Color',[0.8 0.8 0.8], ...
        'Colormap',jet, ...
        'Position',[155 150 600 280], ...
        'Tag','Fig1');
    
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'Callback','voltageBEG run', ...
        'Position',[cols(1) 10 180 64], ...
        'FontSize', 20,...
        'String','Run Voltage', ...
        'Tag','Pushbutton1');
    
    % Pop up for hold off or on.
    b = uicontrol('Parent', a, ...
        'Units','points',...
        'Style','popupmenu',...
        'Position', [cols(1) 70 60 20],...
        'String', {'hold off','hold on'},...
        'Tag', 'PopUp1');
    
    %++BME445/545 LAB_A_CodingTask_II - Adding Code Modification to GUI
    b = uicontrol('Parent', a, ...
        'Units','points',...
        'Style','popupmenu',...
        'Position', [cols(1) 85 60 20],...
        'String', {'Membrane Current'}, ... % {'Membrane Current','G_K', 'G_Na'},...
        'Tag', 'PopUp2');
    %--2022.01.24
    
    %++BME445/545 LAB_A_CodingTask_III - Add Pufferfish Poison option 'Apply TTX' 
    % in PopUp Menu here
    b = uicontrol('Parent', a, ...
        'Units','points',...
        'Style','popupmenu',...
        'Position', [cols(1) 100 60 20],...
        'String', {'no blocker'},... % {'no blocker','block K+', 'block Na+'},...
        'Tag', 'PopUp3');
    %--2022.01.24
    
    % Clamp Voltage 
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'Position',[cols(4) 90 70 30 ], ...
        'String','vclamp (mV)', ...
        'Style','text', ...
        'Tag','StaticText1');
    
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[cols(5) 90 70 30 ], ...
        'String','80', ...
        'Style','edit', ...
        'Tag','clampVoltage');
    
    %++BME445/545 2022.01.24 For LAB_B.
    if 0 % toggle this from 0 --> 1 for March Lab
        modified_visible = 'on';
    else 
        modified_visible = 'off';
    end

    
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'Visible', modified_visible, ...
        'Position',[cols(2) 90 70 30 ], ...
        'String','vclamp0 (mV)', ...
        'Style','text', ...
        'Tag','StaticText1a');
    
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'Visible', modified_visible, ...
        'BackgroundColor',[1 1 1], ...
        'Position',[cols(3) 90 70 30 ], ...
        'String','-5', ...
        'Style','edit', ...
        'Tag','EditText1a');
    
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'Visible', modified_visible, ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'Position',[cols(3)  140 70 15], ...
        'String','t_max(0) (msec)', ...
        'Style','text', ...
        'Tag','StaticText2a');
    
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'Visible', modified_visible, ...
        'BackgroundColor',[1 1 1], ...
        'Position',[cols(3)  160 70 30 ], ...
        'String','0', ...
        'Style','edit', ...
        'Tag','EditText2a');
    %--BME445/545 Lab_B.
    
    %t_delay0
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'Position',[cols(1)  140 70 15], ...
        'String','t_delay(0) (msec)', ...
        'Style','text', ...
        'Tag','StaticText2');
    
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[cols(1)  160 70 30 ], ...
        'String','0', ...
        'Style','edit', ...
        'Tag','t_delay0');
    
    % t_delay1
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'Position',[cols(2) 140 70 15], ...
        'String','t_delay(1) (msec)', ...
        'Style','text', ...
        'Tag','StaticText3');
    
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[cols(2) 160 70 30 ], ...
        'String','5', ...
        'Style','edit', ...
        'Tag','t_delay1');
    
    % y_min
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'Position',[cols(4) 140 70 15], ...
        'String','ymin', ...
        'Style','text', ...
        'Tag','StaticText4');
    
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[cols(4) 160 70 30 ], ...
        'String','-2000', ...
        'Style','edit', ...
        'Tag','y_min');
    
    % y_max
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'Position',[cols(5) 140 70 15], ...
        'String','ymax', ...
        'Style','text', ...
        'Tag','StaticText5');
    
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[cols(5) 160 70 30 ], ...
        'String','5000', ...
        'Style','edit', ...
        'Tag','y_max');
    
    % [Na]_out_
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'Position',[cols(4) 50 70 30 ], ...
        'String','[Na]out', ...
        'Style','text', ...
        'Tag','StaticText6');
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[cols(5) 50 70 30 ], ...
        'String','440', ...
        'Style','edit', ...
        'Tag','na_out');
    
    % eNa
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'Position',[cols(4) 10 70 30 ], ...
        'String','eNa', ...
        'Style','text', ...
        'Tag','StaticText7');
    b = uicontrol('Parent',a, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[cols(5) 10 70 30 ], ...
        'String','117.0028', ...
        'Style','edit', ...
        'Tag','eNa');
    